public with sharing class MethodologyConstants {

    public static final String PROJECT_STATUS_NOT_STARTED = 'Not Started';
    public static final String PROJECT_STATUS_COMPLETED = 'Completed';
    public static final String PROJECT_STATUS_REFRESH ='Refresh Needed';
    public static final String PROJECT_NOT_STARTED ='Not Started';
    public static final String PROJECT_STATUS_STAGE2 ='In Progress - Stage2 : Project Parameters set';
    public static final String PROJECT_STATUS_DONE = 'Done';

    public static final String ROLE_PROJECT_MANAGER='Project Manager'; 
    public static final String ROLE_DELIVERY_LEAD='Delivery Lead';
    public static final String BLANK='';

    public static final String METHOD_TYPE_MICRO='micro';
    public static final String METHOD_TYPE_SMALL='small';
    public static final String METHOD_TYPE_MEDIUM='medium';
    public static final String METHOD_TYPE_LARGE='large';
    public static final String METHOD_TYPE_PROGRAM='program';
    public static final String METHOD_LARGE_SCALE_PROGRAM='large scale program';

    public static final String NICE_TO_USE ='Nice to Use';
    public static final String SHOULD_USE ='Should Use';
    public static final String MUST_USE ='Must Use';

    public Static final String STATUS_DELIVERED = 'Delivered'; 
    public Static final String STATUS_COMPLETED = 'Completed'; 
    public Static final String STATUS_CANCELLED = 'Cancelled'; 
    public Static final String STATUS_SCHEDULED = 'Scheduled'; 



    public static final Integer DEFAULT_BATCH_SIZE = 200; 

    public static final String KEY_OFFERING_DPOC_MAP = 'offeringDPOCMap';
    public static final String KEY_PROJECT_PRODUCT_LIST = 'projectProductList';
    public static final String KEY_PROJECT_ASSIGNMENT_MAP = 'projectAssignmentMap';
    public static final String KEY_METHODOLOGY_CONFIG_MAP = 'methodologyConfigMap';
    public static final String KEY_OPPORTUNITY_MAP = 'opportunityMap';
    public static final String KEY_MFE_LIST ='mfeListToBeUpdated';
    public static final String KEY_OFFERING_CONTRIBUTION_MAP = 'offeringContributionMap';
    public static final String KEY_PROJECT_OFFERING_LIST_MAP = 'projectOfferingListMap';
    public static final String KEY_PLAYBOOK_STAGES_MAP = 'playbookStagesMap';
    public static final String KEY_STAGE_METHODS_MAP = 'stageMethodsMap';
    public static final String KEY_DEFAULT_DPOC = 'defaultDPOC';
    public static final String KEY_WORK_UNIT_DPOC_MAP = 'workUnitDPOCMAp';

    public static final String OFFERING_CUSTOM_SERVICES = 'Custom Services';
    public static final String OFFERING_SOW_PROJECT = 'SOW Project';
    public static final String OFFERING_DEFAULT = 'Default';
    public static final String OFFERING_PHASE_0_STRATEGIC_PLANNING= 'Phase 0 - Strategic Planning';

    public static final String OFFERING = 'Offering';
    public static final String WORK_UNIT = 'Work Unit';

    public static final String PLAYBOOK = 'Playbook';
    public static final String PLAYBOOK_STAGE = 'Playbook Stage';
    public static final String PUBLISHED = 'Published';
    

    public static final String METHODOLGY_SPSM_PROJECT = 'SPSM - Project';
    public static final String METHODOLGY_SPSM_SERVICES_EXPERT_HOURS = 'SPSM - Services Expert Hours';
    public static final String METHODOLOGY_CONFIG_CLASS_NAME = 'ProjectMethodCalculationsBatchHandler';
}