@isTest
private class Orgrefresh_PollScoresTest {
    
    /*@isTest static void testScheduleOauth() {
        
        System.debug('===starting testScheduleOauth====');

        Org_Refresh_Profile__c refreshProfile=OrgRefresh_PrepTestData.createRefreshProfileData(OrgRefresh_AuthFlows.OAUTH_REFRESHTOKEN);
        insert refreshProfile;

        PA_Onboarding_Property__c propertyInstance=OrgRefresh_PrepTestData.createPAOnboardingSelectedOrg('Test Class Created Org');
        insert propertyInstance;
        

        Test.startTest(); 

        OrgRefresh_SetupController setUpCtrl=new OrgRefresh_SetupController();
        Test.setMock(HttpCalloutMock.class, new OrgRefresh_MockCertDataFetchTest());
          //set the selected org name
        setUpCtrl.selectedOrg='Test Class Created Org';
        
        setUpCtrl.startFetchJob();
        
       Test.stopTest();
    }*/
    
}