public with sharing class SolutionFinderConstants {
    
    public final static String ASSIGNMENT_INDEX_NAME = 'ast';
    public final static String BUZZ_WORD_INDEX_NAME = 'buz';
    public final static String DETAIL_INDEX_NAME = 'det';
    public final static String OPTION_INDEX_NAME = 'opt';
    public final static String COMPARISON_PROPERTY = 'cpr';
    public final static String RECOMMENDATION_INDEX_NAME = 'rec';
    public final static String SOLUTION_INDEX_NAME = 'sol';
    public final static String WORD_ASSOCIATION_INDEX_NAME = 'wda';
}